### ISSUE TITLE
ccache doesn't understand -fprofile-correction

### ISSUE THREAD

**Issue by schnitzeltony** [ccache/ccache#615]
I did send an upgrade ccache 3.7.9 -> 3.7.10 to Openembedded. Was under the impression my build tests did enable ccache but they did not - did change the wrong configuration. So my change was not tested properly. Now there are reports of errors building python 3.8.3 like:

| Python-3.8.3/Modules/_contextvarsmodule.c:43:1: error: source locations for function 'PyInit__contextvars' have changed, the profile data may be out of date [-Werror=coverage-mismatch]

And yes am not an ccache user/expert so: What can I do to find more information what causes this?

**Comment by AlexanderLanin** [comment]
Just to confirm I understand correctly: Everything was fine with ccache 3.7.9, the only change is ccache version and now it doesn't compile?
That's of course not ideal for you, but kind of ideal for bug hunting. Only a very limited number of possible causes: https://github.com/ccache/ccache/compare/v3.7.9...v3.7.10

Is there any way to easily reproduce the problem in order to bisect which change is responsible?

**Comment by schnitzeltony** [comment]
> Just to confirm I understand correctly: Everything was fine with ccache 3.7.9, the only change is ccache version and now it doesn't compile?

Yes exactly - was reported and I verified it.
> That's of course not ideal for you, but kind of ideal for bug hunting. Only a very limited number of possible causes: v3.7.9...v3.7.10

That looks indeed perfectly suited for bisect. Will do that and report.

For reference: OE patch/error report is at  https://lists.openembedded.org/g/openembedded-core/topic/75170448#140065

**Comment by schnitzeltony** [comment]
Bisect result:

c9fdcef576dd13a2ea2355bcd866b5c561cb1562 is the first bad commit

**Comment by jrosdahl** [comment]
> And yes am not an ccache user/expert so: What can I do to find more information what causes this?

There is no special information to read about this; it simply looks like a bug. The commit you mention improved the handling of profiling options (so it was the quite obvious suspect of the few changes that went into 3.7.10…) since it had several bugs. Apparently some other aspect broke in the process.

To be able to fix the bug we need to know how to reproduce the problem. Could you please submit a bug report on https://github.com/ccache/ccache/issues/new/choose and describe what environment you use and what steps to run to trigger the problem?

I read some instructions on http://www.openembedded.org but they only leave me confused. I've also tried to build Python with

```console
make build_all_generate_profile
make run_profile_task
make build_all_merge_profile
make clean
make build_all CFLAGS_NODIST=" -fprofile-use -fprofile-correction" LDFLAGS_NODIST=""
```

(commands taken from the log file mentioned in https://lists.openembedded.org/g/openembedded-core/topic/75170448#140065) but it works fine for me.

**Comment by schnitzeltony** [comment]
Have written this in the original thread: Am packing and will be out for vacation next two weeks - sorry for poor timing.

Ahh and if you want to try to reproduce:

1. Use Yocto docs [1] they are far better and OE-docs are outdated
2. If you want to build ccache-native from git sources: For bisecting I created a hack for that [2]

[1] https://www.yoctoproject.org/docs/
[2] https://github.com/schnitzeltony/openembedded-core/tree/ccache-bisect-hack

**Comment by jrosdahl** [comment]
> Have written this in the original thread: Am packing and will be out for vacation next two weeks - sorry for poor timing.

Have a nice vacation!

> Ahh and if you want to try to reproduce:
> 
> 1. Use Yocto docs [1] they are far better and OE-docs are outdated

That doesn't help much I'm afraid. I have zero experience with openembedded and Yocto (had never heard of them before). I don't know which version to build, and how to build, to trigger the problem. Some simple hints on what to do would save a lot of time.

> 2. If you want to build ccache-native from git sources: For bisecting I created a hack for that [2]

Building ccache is something I do know, though, and there's no need to bisect. :wink:

**Comment by lumag** [comment]
@jrosdahl we have stumbled upon this issue in Yocto/OE builds, thus we are pointing to Yocto/OE. Maybe you can reproduce the issue when cross-compiling python3 with gcc-9 to armv8 (aarch64).

**Comment by jrosdahl** [comment]
> @jrosdahl we have stumbled upon this issue in Yocto/OE builds, thus we are pointing to Yocto/OE. Maybe you can reproduce the issue when cross-compiling python3 with gcc-9 to armv8 (aarch64).

@lumag: Thanks for the hint, but no such luck:

```console
% make run_profile_task
./python -m test --pgo || true
/bin/sh: 1: ./python: Exec format error
```

In your log file `make run_profile_task` runs `./pgo-wrapper` which I don't what it is.

**Comment by jrosdahl** [comment]
@Mingli-Yu kindly shared in python/cpython#21408 how to reproduce the issue:

> 1, mkdir -p /build/yocto/build
> 2, cd /build/yocto
> 3, git clone git://git.yoctoproject.org/poky
> 4, cd poky
> 5, git revert 9e856a0a1a76bc4ba5fa050be038dd702cc58185
> Note: the step 5 used to remove my fix
> 6, sed -i 's:INHERIT += "reproducible_build":#INHERIT += "reproducible_build":' ./meta-poky/conf/distro/poky.conf
> Note: the step 6 just used to enable profile guided optimizations (PGO) for python3
> 7, . oe-init-build-env ../build/poky-build
> 8, bitbake python3
> After the step 8 finish, check the compile log tmp/work/core2-64-poky-linux/python3/3.8.3-r0/temp/log.do_compile for details.

ccache doesn't seem to be used when following the above steps. I also tried to install ccache using the [masquerading method with symlinks](https://ccache.dev/manual/3.7.10.html#_run_modes), but then I get an error like this:

```
ERROR: Error running gcc  --version: ccache: error: Could not find compiler "gcc" in PATH
```

This is because the PATH variable that ccache gets from bitbake does not include `/usr/bin` or `/usr/local/bin`, etc. (If the build is isolated, why does Yocto/bitbake find my ccache symlink in $HOME/bin?)

What is missing from the reproduction steps, i.e. how to enable ccache in Yocto?

**Comment by Mingli-Yu** [comment]
Sorry I miss some steps,  please follow the below steps again.
1, mkdir -p /build/yocto/build
2, cd /build/yocto
3, git clone git://git.yoctoproject.org/poky
4, cd poky
5, git revert 9e856a0a1a76bc4ba5fa050be038dd702cc58185
Note: the step 5 used to remove my fix
6, sed -i 's:INHERIT += "reproducible_build":#INHERIT += "reproducible_build":' ./meta-poky/conf/distro/poky.conf
Note: the step 6 just used to enable profile guided optimizations (PGO) for python3
7, echo "INHERIT += \"ccache\"" >> conf/local.conf
echo "CCACHE_DIR = \"\${TMPDIR}/ccache/\${MULTIMACH_TARGET_SYS}/\${PN}\"" >> conf/local.conf
Note: the step 7 is used to enable ccache
8, . oe-init-build-env ../build/poky-build
9, bitbake python3
After the step 9 finish, check the compile log tmp/work/core2-64-poky-linux/python3/3.8.3-r0/temp/log.do_compile for details.

**Comment by jrosdahl** [comment]
Thanks!

Looks like step 8 is not quite correct, it should be 

```console
echo 'INHERIT += "ccache"' >> conf/local.conf
echo 'CCACHE_DIR = "${TMPDIR}/ccache/${MULTIMACH_TARGET_SYS}/${PN}"' >> conf/local.conf
```

(single quotes instead of double quotes). Also, step 7 doesn't work with zsh so then one either has to switch to bash or run `. ./oe-init-build-env ../build/poky-build` instead.

With the mentioned changes I'm able to reproduce the problem. :tada:

**Comment by jrosdahl** [comment]
After several hours spread out over several days battling with the Yocto build system I learned enough to be able to debug the issue with a 1 minute (instead of 1 hour) turnaround time. I now know what the problem is:

1. In Yocto, Python is first built with `-fprofile-generate`, then a Python test suite is run to collect profiling information and finally Python is rebuilt with `-fprofile-use -fprofile-correction` using the collected profiling data.
2. Yocto sets `CCACHE_BASEDIR` to rewrite absolute paths to relative.
3. The Python build system uses absolute paths in command lines.
4. ccache ≤3.7.9 is forgiving about profiling options that it doesn't know about. In particular, `-fprofile-correction` is unknown but ignored with a note in the ccache log.
5. ccache 3.7.10 has much better knowledge about semantics of the different profiling options. In an effort to avoid bad output when unknown profiling options are used, ccache 3.7.10 gives up when it sees an unknown compiler option and just executes the real compiler with the original command line. `-fprofile-correction` is still an unknown option.
6. When Yocto builds Python with ccache 3.7.10, the `-fprofile-generate` step works like before, and points 2+3 above makes the compiler see **relative paths** on the command line. But due to point 5 above, the `-fprofile-use` step makes ccache just pass through to the real compiler, using **absolute paths**.
7. When GCC sees absolute paths instead of the relative paths recorded in the collected profiling data it emits `-Werror=coverage-mismatch` errors.

I'll convert this support issue to a bug and add knowledge about `-fprofile-correction` in ccache 3.7.11. That should fix the problem.
