### ISSUE TITLE
False positive direct cache hit when ccache has disabled direct mode

### ISSUE THREAD

**Issue by sandsmark** [ccache/ccache#935]
See the attached file containing commands run, as well as artifacts + ccache debug files.

The good/ subfolder contains the correct .o file when running clang++ directly instead of ccache.

[ccache-bug.tar.gz](https://github.com/ccache/ccache/files/7186732/ccache-bug.tar.gz)

```
ccache-bug/
ccache-bug/build-commands
ccache-bug/good/
ccache-bug/good/Viewer_moc.cpp.o
ccache-bug/ccache/
ccache-bug/ccache/Viewer_moc.cpp.o.ccache-input-c
ccache-bug/ccache/Viewer_moc.cpp.o.ccache-input-text
ccache-bug/ccache/Viewer_moc.cpp.o.ccache-log
ccache-bug/ccache/Viewer_moc.cpp.o.ccache-input-d
ccache-bug/ccache/Viewer_moc.cpp.o
ccache-bug/ccache/Viewer_moc.cpp.o.d
```

### How to reproduce ###

Run ccache to output an .o file:

```
/usr/lib/ccache/bin/clang++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/home/sandsmark/src/qeh/build-qeh-clang-Debug -I/home/sandsmark/src/qeh -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -fdiagnostics-color=always -g -fPIC -std=gnu++11 -MD -MT CMakeFiles/qeh.dir/Viewer_moc.cpp.o -MF CMakeFiles/qeh.dir/Viewer_moc.cpp.o.d -o CMakeFiles/qeh.dir/Viewer_moc.cpp.o -c /home/sandsmark/src/qeh/build-qeh-clang-Debug/Viewer_moc.cpp
```

### Actual behavior ###

Got an outdated .o file:

```
$ /usr/bin/clang++ -fdiagnostics-color=always -g  CMakeFiles/qeh.dir/main.cpp.o CMakeFiles/qeh.dir/Viewer.cpp.o CMakeFiles/qeh.dir/Viewer_moc.cpp.o -o qeh  /usr/lib/libQt5Widgets.so.5.15.2  /usr/lib/libQt5Gui.so.5.15.2  /usr/lib/libQt5Core.so.5.15.2
/usr/bin/ld: CMakeFiles/qeh.dir/Viewer_moc.cpp.o:(.data.rel.ro+0xd8): undefined reference to `Viewer::mousePressEvent(QMouseEvent*)'
/usr/bin/ld: CMakeFiles/qeh.dir/Viewer_moc.cpp.o:(.data.rel.ro+0x148): undefined reference to `Viewer::closeEvent(QCloseEvent*)'
```

### Expected behavior ###

Get an up to date .o file.

```
$ /usr/bin/clang++ -fdiagnostics-color=always -g  CMakeFiles/qeh.dir/main.cpp.o CMakeFiles/qeh.dir/Viewer.cpp.o CMakeFiles/qeh.dir/Viewer_moc.cpp.o -o qeh  /usr/lib/libQt5Widgets.so.5.15.2  /usr/lib/libQt5Gui.so.5.15.2  /usr/lib/libQt5Core.so.5.15.2
$
```

### Environment ###
ccache version 4.4

ext4 on a local disk with relatime turned on.

It seems like a recent regression, which seems very plausible because of the new complex storage stuff that has been added. It only spuriously seems to get in this state but when it happens it will consistently fetch the old blob from the cache, so I assume it somehow copies over the old blob to the new hash? Unfortunately I didn't have debug turned on before the bug started happening, so I don't have logs from when it (presumably) did that.

This is probably also what the guy in https://github.com/ccache/ccache/issues/926 saw, so it's not just something local here.

**Comment by craigbarnes** [comment]
I think I've been having the same issue, since upgrading to 4.4.0.

In one of my projects, I use a git `pre-commit` [hook] that runs a bunch of tests, including [checking] the generated version number is as expected and since upgrading past 4.4.0, this check periodically fails, seemingly because of a false positive cache hit for the object compiled for the previous commit. I can tell this because the test failure reports the expected and actual version numbers.

[hook]: https://gitlab.com/craigbarnes/dte/-/blob/09907380deea0a7bf111dbefb3d0b3601eb8799c/tools/git-hooks/pre-commit
[checking]: https://gitlab.com/craigbarnes/dte/-/blob/09907380deea0a7bf111dbefb3d0b3601eb8799c/test/check-opts.sh#L31

FWIW, my `ccache.conf` contains:

```
file_clone = true
max_size = 8.0Gi
```

I've been using that config for while now, but never had any problems until after 4.4.0.

When it happens, I've been deleting the entire cache, but it always seems to occur again eventually.

**Comment by jrosdahl** [comment]
Thanks for the bug report. I agree that something seems fishy since several people now have reported similar issues.

@sandsmark wrote:

> It seems like a recent regression, which seems very plausible because of the new complex storage stuff that has been added.

It's true that the storage backend code changed a lot in version 4.4, but that code is not involved in any code paths that affect how ccache collects information for the input hash. But since code has been moved and refactored, some mistake that does affect the input hash could of course have been made along the way.

> It only spuriously seems to get in this state but when it happens it will consistently fetch the old blob from the cache, so I assume it somehow copies over the old blob to the new hash?

For a false positive cache hit to happen, there has to be a case where the old compilation and the new compilation have the _same_ hash. Unless there is a _very_ strange bug in the storage backend code.

> Unfortunately I didn't have debug turned on before the bug started happening, so I don't have logs from when it (presumably) did that.

Right, that's understandable. Unfortunately there is not much I can do with the currently available information. What's needed to debug a false positive cache hit is knowledge about what difference (in the source code, compiler flags or environment) between the old and new compilation that ccache should have picked up but didn't. The content of the manifest file for the cache hit (`/home/sandsmark/.ccache/e/4/d58e3ih2uhmvtbhvof7jv5gevu5ji02M` in your example) is also of interest. 

I notice that both you and @bartoszek (in #926) describe builds of Qt-based code. @craigbarnes: Is that the case for you as well?

Another thing that would be very interesting to know is if you get false positive cache hits when disabling the direct mode (with `CCACHE_NODIRECT=1` or `direct = false` in `ccache.conf`).

The best thing would of course be a way to easily reproduce the problem. @neheb: In nih-at/libzip#257 you said that the bug is very easy to reproduce. Perhaps you can share how to do it?

**Comment by neheb** [comment]
Hehehe. It’s very easy to reproduce with OpenWrt, but asking to set up an entire environment is a bit much.

libzip basically has multiple build variants in OpenWrt that use different options. I guess this could be reproduced by placing libzip in multiple directories with different cmake options. It probably helps to try the nossl variant last.

Here are the relevant options used in OpenWrt: https://github.com/openwrt/packages/blob/master/libs/libzip/Makefile#L85

**Comment by craigbarnes** [comment]
> I notice that both you and @bartoszek (in #926) describe builds of Qt-based code. @craigbarnes: Is that the case for you as well?

No, there's no libraries involved in my case (except libc). Next time it happens I'll try to preserve the state of the cache and the build environment and try to come up with a way to reproduce it (if someone else doesn't beat me to it).

**Comment by quark17** [comment]
I noticed that the CI for [bsc](https://github.com/B-Lang-org/bsc) has a predictable failure on the macOS VM, which started when the version of ccache changed from 4.3_1 to 4.4.  (We use HomeBrew to install tools and they updated to 4.4; so we're working around it by holding HomeBrew back to the older version.)  I am able to reproduce this locally on my Mac (where things compile fine without ccache but break when ccache 4.4 is introduced.)

I am working on boiling it down to a small example, but if you're up to cloning and building the whole BSC project, you can repeat the error with the following commands (after installing the required tools):
```
# build BSC
$ make install-src

# run specific tests that fail
$ ccache --zero-stats --max-size 250M
$ cd testing/bsc.lib/PAClib/
$ make check
```
(Note that you can also download a pre-built tarball of BSC, instead of building it yourself.)

The last line runs a series of tests in that directory, which are variants of the same code: there's a top object which is the testbench (named `mkTb`) and that instantiates different objects under test.  So these different directories share common names, and in some cases, the code is very similar.  The subdirectory `RadixSort` has four subdirectories of the same object-under-test (so not only is `mkTb` the same across each, but the object under that has the same name and same prototype); the subdirectory `qsort` has a `mkTb` top, but the object-under-test is different from `RadixSort`.  This exposes two types of errors: first, the compile in `RadixSort/rev3/` succeeds in producing an executable, but segfaults when run (maybe it's using an earlier cached object from `rev2` or `rev1`?); second, the compile in `qsort` fails to link, with an error about undefined symbols ... which are not symbols in `qsort` but are symbols in `RadixSort`, indicating that ccache has mistakenly reused an object from `RadixSort`.

I am working on building a small example, so that you don't need to have BSC or its testing infrastructure.

**Comment by quark17** [comment]
With `CCACHE_NODIRECT=1`, the BSC example works fine (presumably does not have false positive cache hits).

(And sorry for the multiple commit references to this PR, as I was experimenting with holding back the version in our CI.)

**Comment by jrosdahl** [comment]
@quark17 wrote:

> I am working on boiling it down to a small example

That would be awesome!

> you can repeat the error with the following commands (after installing the required tools):
>
> ```
> # build BSC
> $ make install-src
> 
> # run specific tests that fail
> $ ccache --zero-stats --max-size 250M
> $ cd testing/bsc.lib/PAClib/
> $ make check
> ```

I couldn't reproduce the problem with the above on my Linux system. Here's what I did:

```
git clone --recurse-submodules https://github.com/B-Lang-org/bsc.git
cd bsc
make install-src
cd testsuite/bsc.lib/PAClib
make check
```

Both with and without ccache I get this from `make check`:

```
[...]
		===  tests ===

Schedule of variations:
    unix
[...]
Running ./RadixSort/rev1/paclib_radix_rev1.exp ...
Running ./RadixSort/rev2/paclib_radix_rev2.exp ...
Running ./RadixSort/rev3/paclib_radix_rev3.exp ...
Running ./RadixSort/rev4/paclib_radix_rev4.exp ...
Running ./dft64/bsv/paclib_dft.exp ...
Running ./qsort/bsv/paclib_qsort.exp ...
Running ./unit_tests/unit_test.exp ...
FAIL: `sysForFold_1.v' should link to executable `sysForFold_1'
FAIL: Verilog simulation `sysForFold_1' should execute: child process exited abnormally
[...]
FAIL: `sysWhileLoop.v.out' differs from `sysWhileLoop.out.expected'
FAIL: Verilog simulation `sysWhileLoop' should execute with VCD dump: child process exited abnormally
[...]
# of expected passes		123
# of unexpected failures	48
make: *** [/bigdisk/tmp/bsc/testsuite/suitemake.mk:97: check] Error 1
```

No signs of any segfaults or linking errors, unfortunately.

> I am working on building a small example, so that you don't need to have BSC or its testing infrastructure.

Again, that would be appreciated, but not really necessary if I just can get hold of a reproducible scenario to work with.

**Comment by quark17** [comment]
I am able to reproduce my failures on a Debian 10 system .  The ccache is 4.4.1 that I downloaded from source and built -- using zstd, hiredis, etc installed via the package manager for Debian 10, so presumably not the latest versions.  The `c++` is also the version installed via the package manager for Debian 10, which appears to be GCC 8.3.0 (Debian 8.3.0-6), if that's relevant.

I am able to do this:
```
$ ccache -C
Clearing... 100.0% [===================================================================================================]
$ make check
...
Running ./RadixSort/rev1/paclib_radix_rev1.exp ...
Running ./RadixSort/rev2/paclib_radix_rev2.exp ...
Running ./RadixSort/rev3/paclib_radix_rev3.exp ...
FAIL: Bluesim simulation `sysTb' should execute: child process exited abnormally
FAIL: `sysTb.c.out' differs from `sysTb.out.expected'
FAIL: Bluesim simulation `sysTb' should execute: child process exited abnormally
Running ./RadixSort/rev4/paclib_radix_rev4.exp ...
Running ./dft64/bsv/paclib_dft.exp ...
Running ./qsort/bsv/paclib_qsort.exp ...
FAIL: Bluesim simulation `sysTb' should execute: child process exited abnormally
FAIL: `sysTb.c.out' differs from `sysTb.out.expected'
FAIL: Bluesim simulation `sysTb' should execute: child process exited abnormally
Running ./unit_tests/unit_test.exp ...
...
# of expected passes		165
# of unexpected failures	6
```
and then I can do this, setting nodirect to true:
```
$ ccache -C
Clearing... 100.0% [===================================================================================================]
$ CCACHE_NODIRECT=1 make check
...
Running ./RadixSort/rev1/paclib_radix_rev1.exp ...
Running ./RadixSort/rev2/paclib_radix_rev2.exp ...
Running ./RadixSort/rev3/paclib_radix_rev3.exp ...
Running ./RadixSort/rev4/paclib_radix_rev4.exp ...
Running ./dft64/bsv/paclib_dft.exp ...
Running ./qsort/bsv/paclib_qsort.exp ...
Running ./unit_tests/unit_test.exp ...
...
# of expected passes		171
```
If you are unable to reproduce this, I would be happy to run any commands for you, to produce diagnostic output, if that's useful.

I don't know why you're seeing the Verilog failures.  We could debug that, but I'm not sure it's relevant.  (The output of the command that failed would be in `unit_tests/sysForFold_1.bsc-vcomp-out`, if you wanted to look.)

I did not have any success in making an example that didn't use BSC, however, I could boil it down to a series of calls to BSC (not requiring the testsuite infrastructure).  BSC generates `.h` and `.cxx` files and executes `c++` to compile and link them.  I attempted to manually run those `c++` commands, but it did not trigger a ccache problem; it was only when BSC ran them, that I could produce the problem.

**Comment by jrosdahl** [comment]
@quark17 wrote:

> I am able to reproduce my failures on a Debian 10 system

I tried to reproduce the problem in a Debian 10 Docker container without any luck.

Here's how to try what I did:

1. Have a working Docker installation.
2. Download and untar [repro.tar.gz](https://github.com/ccache/ccache/files/7238872/repro.tar.gz).
3. Run `./repro-in-docker`. It first builds an environment image with needed dependencies (including ccache 4.4.1) and a `repro` script which it then executes inside a container. The `repro` script clones and builds bsc and runs the PAClib tests.

Result for me:

```
[...]
		===  Summary ===

# of expected passes		171
```

Could you have a look and see if `Dockerfile` and `repro` look like you expect? And does the script reproduce the problem when you run it? If not, any ideas and tweaks that makes it reproduce the problem would be highly appreciated.

**Comment by quark17** [comment]
I haven't used Docker, so I will have to figure out how to set that up, in order to run anything.  In the meantime, the only difference I can see is that I don't use ccache while building BSC (just before `make check` is when I add it to the path or clear the cache).  I had also been setting a max size, but if I unset that, I still see a failure.  I also wasn't setting environment variables for the logfile and debug, but if I do that I still see the errors, so that's not the difference.

I am able to look in the logs and see that the `qsort` directory does report a (false) hit for `sysTb.o`; even though `sysTb.cxx` is identical to that used for `RadixSort`, there is a one-line difference in `sysTb.h` that changes the type of a class member (leading to the undefined-symbol error).  For the segfault in `RadixSort/rev3`, there's a hit on `sysTb.o` but that's OK because the `h` and `cxx` files are identical to those in the `rev2` and `rev1` directories; there was no other hit.  So something else must be going wrong there.

I guess another difference is that I didn't build ccache with `-j`, but I can't imagine that would matter?  I also used `-DCMAKE_BUILD_TYPE=Release`, and I used `-DCMAKE_INSTALL_PREFIX` to install it into a subdirectory in my homedir.  (On the macos CI and on a macos laptop, where it fails in both place, we use Homebrew to install, and I'd have to see how it builds ccache.)  I also see that you installed the ccache package with `apt-get`, but then replaced its binary with the 4.4.1 build; I guess that's so you can use the `/usr/lib/ccache` directory in the path.  On the Debian 10 where I installed the binary into my homedir, I just manually created a link for `c++` in that same subdirectory.  But I can't imagine any of this matters?

**Comment by yashi** [comment]
Just wanted to drop a line saying that I've been seeing wrong compilations locally a few time in this week.  Unfortunately, I can't reproduce it yet.  I saw wrong compilation with both CMake and Meson on Debian Sid.  I've now downgraded from ccache 4.4-1 to 4.2-1 to see how it behaves.

**Comment by sandsmark** [comment]
It seems related to header change tracking. It happened again now, and no matter how much I changed the header it didn't pick up on it, but when I changed the .cc file it started picking up changes in the header again.

What I also noticed was that while it was failing it didn't write create a `main.cc.o.ccache-input-p` with debug turned on, but when I changed the .cc file it created it and started picking up changes in the headers again.

So I assume it is related to the header tracking in direct mode (as kind of confirmed already), though now that I "fixed" it by changing the .cc file I can't see if turning off direct mode fixes it.

>What's needed to debug a false positive cache hit is knowledge about what difference (in the source code, compiler flags or environment) between the old and new compilation that ccache should have picked up but didn't.

It's the content of the files that change, nothing else.

Attached the debug files from another failure, including the manifest files etc., in case it helps: [ccache-fail.tar.gz](https://github.com/ccache/ccache/files/7244499/ccache-fail.tar.gz)

**Comment by olupton** [comment]
I have also been trying to understand what looks to be the same issue (ccache 4.4.1).

As noted above, it seems that in the right circumstances ccache fails to notice that a header has been modified. I could reproduce the error by populating a cache (`build-master-new`, `build-master-new2`), then modifying a header and building against the same cache (`build-746ae...-new`). Of course building with a clean cache directory (`build-746ae...-cleanccache`) gave correct results. I tried to collect all the relevant files here: [ccache-debug.tar.gz](https://github.com/ccache/ccache/files/7245065/ccache-debug.tar.gz), but I wasn't confident which files I should be including from the cache directory.
 
In my case, disabling direct mode avoids the problem.

---

Some more details about the test setup I used and the files included in the tarball above follow. The difference that ccache misses can be seen be comparing the preprocessed output in:
```
build-master-new/test/unit/CMakeFiles/testcodegen.dir/codegen/codegen_ispc.cpp.o.ccache-input-text
build-746aed7f3ee8849dfff6423bb5d7b93b6aa07c0e-cleanccache/test/unit/CMakeFiles/testcodegen.dir/codegen/codegen_ispc.cpp.o.ccache-input-text
```
which were two runs with clean caches. The header `/Users/olupton/build/nmodl/src/codegen/codegen_c_visitor.hpp` is included and has changed.

The sequence of events is:
- Clean build, original file (`build-master-new/test/unit/CMakeFiles/testcodegen.dir/codegen/codegen_ispc.cpp.o.ccache-log`): cache miss
- Rebuild (i.e. clean build directory, cache left alone) (`build-master-new2/test/unit/CMakeFiles/testcodegen.dir/codegen/codegen_ispc.cpp.o.ccache-log`): direct cache miss, preprocessed cache hit
- Change header file content, cache left alone (`build-746aed7f3ee8849dfff6423bb5d7b93b6aa07c0e-new/test/unit/CMakeFiles/testcodegen.dir/codegen/codegen_ispc.cpp.o.ccache-log`): direct cache hit, false positive

**Comment by jrosdahl** [comment]
Thank you all for valuable efforts and input! @olupton's files contained enough information that I managed to find the bug! :tada:

And the reason why I couldn't reproduce @quark17's issue earlier is because `/usr/lib/ccache` doesn't contain a symlink for `c++` ([Debian bug #632779](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=632779)) so ccache wasn't actually used for the `make check` part. I didn't think of this since the main build uses `g++` instead of `c++` so the ccache counters indicated that ccache was active. Sigh...

The bug was indeed introduced in a refactoring, and the test suite unfortunately did not have a test case that caught it. The bug happens like this:

1. ccache is called to wrap a compilation of a source file with include files. The direct mode is enabled in the ccache configuration (as it is by default) but ccache disables it during runtime. This can happen for several reasons, for instance when an include file is considered too new (typically because it's generated just before being included; this happens in @quark17's case) or when an include file cannot be found (@olupton's case). ccache stores the result in the cache but does not write a manifest since direct mode was disabled. So far so good.
2. ccache is called once again with exactly the same source file and include files. ccache (a) gets a preprocessed hit from step 1 and (b) something makes ccache disable direct mode once more (likely the same the same reason as before). However, there is now another code path that leads ccache to write a manifest file with _only the include files that it has seen until it decided that the direct mode should be disabled_. This means that a subset of the include files could be missing in the manifest entry.
3. ccache is called once again with the same source file but with a modification in some of the include files that were not included in step 2, leading to a false positive direct hit.
