### ISSUE TITLE
Test fails on NFS and with old objdump

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#639]
### Description ###

This test " debug_prefix_map" fails when i compile ccache in NFS directory. It passes when i run ccache from /export (local disk) directory. It is better to fix it.

--logs--

Skipped test suite sanitize_blacklist [-fsanitize-blacklist not supported by compiler]
Running test suite debug_prefix_map.
FAILED

Test suite:     debug_prefix_map
Test case:      Mapping of debug info CWD
Failure reason: Relocation (dir) not found in test.o

ccache -s:

**Comment by jrosdahl** [comment]
> This test " debug_prefix_map" fails when i compile ccache in NFS directory

Both the debug_prefix_map and the inode_cache suites work fine for me on NFS. I also don't see why those tests would be affected by the underlying file system type. Therefore the next thing to do is to investigate why they fail and fix the issues instead of just skipping them.

Since I can't reproduce the issue I'm afraid it will be up to you to do the debugging. A tip is to run something like `bash -x test/run debug_prefix_map` to get a trace of what the test is doing.

**Comment by dyadav7** [comment]
I am getting this message "Failed to open inode cache" / " Inode cache not supported because the cache file would be located on nfs"  in NFS directory. When in run in local these messages are not there.

[2020-08-28T09:40:34.061851 21436] Apparent working directory: /home/deepaky/temp/ccache/orig/ccache/test/testdir/21363/run
[2020-08-28T09:40:34.062241 21436] Source file: test1.c
[2020-08-28T09:40:34.062256 21436] Object file: test1.o
[2020-08-28T09:40:34.066034 21436] Trying direct lookup
[2020-08-28T09:40:34.066377 21436] Failed to open inode cache /home/deepaky/temp/ccache/orig/ccache/test/testdir/21363/.ccache/tmp/inode-cache.v1: No such file or directory
[2020-08-28T09:40:34.066388 21436] Creating a new inode cache
[2020-08-28T09:40:34.070882 21436] Inode cache not supported because the cache file would be located on nfs: /home/deepaky/temp/ccache/orig/ccache/test/testdir/21363/.ccache/tmp/inode-cache.v1
[2020-08-28T09:40:34.073498 21436] Failed to open inode cache /home/deepaky/temp/ccache/orig/ccache/test/testdir/21363/.ccache/tmp/inode-cache.v1: No such file or directory
[2020-08-28T09:40:34.074099 21436] Looking for result name in /home/deepaky/temp/ccache/orig/ccache/test/testdir/21363/.ccache/4/b/7998e98fd47a427b0baff6d0ada45313ad1e7d.manifest
[2020-08-28T09:40:34.074402 21436] No such manifest file
[2020-08-28T09:40:34.074413 21436] Did not find result name in manifest
[2020-08-28T09:40:34.080083 21436] Running preprocessor

**Comment by jrosdahl** [comment]
> I am getting this message "Failed to open inode cache" / " Inode cache not supported because the cache file would be located on nfs" in NFS directory. When in run in local disk these 2 messages are not there.

The inode cache file is placed in the "ccache temporary directory" (`temporary_dir`) which is located in `/run/user/<UID>/ccache-tmp` if it exists and in `<ccache_dir>/tmp` otherwise. This means that a good fix of the problem would be to let the inode_cache test suite probe whether `temporary_dir` (can be retrieved with `ccache -k temporary_dir`) is on NFS and skip the suite if that's the case.

How about the debug_prefix_map failure? Have you been able to debug that one?

**Comment by dyadav7** [comment]
`$CCACHE -k temporary_dir` can not be executed in PROBE functions as the ccache env setting are not done before PROBLE.
These are set in TEST() only. 
Should i execute `$CCACHE -k temporary_dir` in inode_cache_tests() function ?

I am not able to hit debug_prefix_map failure now.

**Comment by jrosdahl** [comment]
> `$CCACHE -k temporary_dir` can not be executed in PROBE functions as the ccache env setting are not done before PROBLE.

Fixed in 86cb81c3bd91.

**Comment by dyadav7** [comment]
i found debug_prefix_map failure . it happens with gcc version 4.4.7. This test passed with 5.4.0 for me.
The "-fdiagnostics-color unsupported" message comes with 4.4.7. This may be the reason.

[Date PID] Running real compiler
[Date PID] Executing /install/tool//bin/gcc -g -fdebug-prefix-map=/home/user1/temp/ccache/src/ccache/test/testdir/25566/run/dir1=dir -fdiagnostics-color -Iinclude -c -o ./test.o src/test.c
[Date PID] -fdiagnostics-color is unsupported; trying again without it
[Date PID] Executing /install/tool//bin/gcc -g -fdebug-prefix-map=/home/user1/temp/ccache/src/ccache/test/testdir/25566/run/dir1=dir -Iinclude -c -o ./test.o src/test.c
[Date PID] Using default compression level 1

**Comment by jrosdahl** [comment]
No, "-fdiagnostics-color is unsupported" is expected for GCC <4.9 and should not be a problem; notice the "trying again without it" message.

With the hint about GCC 4.4 I can reproduce the error now. It's a regression in #231: Old objdump versions don't print debug info with `objdump -g` like the test expects. I'll think some more about this tomorrow.

**Comment by jrosdahl** [comment]
@dyadav7: Please try latest master now.

**Comment by dyadav7** [comment]
debug_prefix_map passed. now, profiling test failed.

$ bash -x run profiling
...
+ gcc -fprofile-generate=data test.o -o test
test.o: In function `main':
test.c:(.text+0x1d): undefined reference to `__gcov_indirect_call_profiler'
test.o: In function `global constructors keyed to 65535_0_main':
test.c:(.text+0x4f): undefined reference to `__gcov_init'
test.o:(.data+0x48): undefined reference to `__gcov_merge_add'
collect2: ld returned 1 exit status
+ ./test

----
Running test suite profiling.....test.o: In function `main':
test.c:(.text+0x1d): undefined reference to `__gcov_indirect_call_profiler'
test.o: In function `global constructors keyed to 65535_0_main':
test.c:(.text+0x4f): undefined reference to `__gcov_init'
test.o:(.data+0x48): undefined reference to `__gcov_merge_add'
collect2: ld returned 1 exit status
./suites/profiling.bash: line 79: ./test: No such file or directory
test.c: In function 'main':
test.c:1: note: file data/test.gcda not found, execution counts assumed to be zero

FAILED

Test suite:     profiling
Test case:      -fprofile-use=dir
Failure reason: Expected "cache miss" to be 2, actual 1

**Comment by jrosdahl** [comment]
> `test.o: In function main': test.c:(.text+0x1d): undefined reference to __gcov_indirect_call_profiler'`

I think this should be fixed by 84c54fbb5636.

Tip: Use [triple backticks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) when including command output in a comment.

**Comment by dyadav7** [comment]
All tests are now passing with gcc 4.4.7.
