### ISSUE TITLE
Build failure on OS X 10.8-10.11 due to _mm512_loadu_si512, _mm256_set1_epi8, etc.

### ISSUE THREAD

**Issue by ryandesign** [ccache/ccache#689]
Hi, I'm the maintainer of [ccache in MacPorts](https://ports.macports.org/port/ccache). After updating to 4.0 it became apparent that it doesn't build anymore on some older macOS versions for various reasons. 4.0 does build on 10.13 and up. 3.7.12 and earlier built fine on older macOS versions down to 10.6 or maybe even earlier.

### How to reproduce ###

1. Compile ccache 4.0 on OS X 10.8 thru 10.11

### Actual behavior ###

On 10.10 and 10.11 there are many errors like:

https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/125455/steps/install-port/logs/stdio
https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/123825/steps/install-port/logs/stdio

```
src/third_party/blake3/blake3_avx512.c:18:10: warning: implicit declaration of function '_mm512_loadu_si512' is invalid in C99 [-Wimplicit-function-declaration]
  return _mm512_loadu_si512((const __m512i *)src);
         ^
src/third_party/blake3/blake3_avx512.c:18:10: error: returning 'int' from a function with incompatible result type '__m512i' (vector of 8 'long long' values)
  return _mm512_loadu_si512((const __m512i *)src);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

On 10.8 and 10.9 there are many errors like:

https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/27906/steps/install-port/logs/stdio
https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/129032/steps/install-port/logs/stdio

```
src/hashutil.cpp:128:18: warning: unknown attribute 'target' ignored [-Wattributes]
  __attribute__((target("avx2")));
                 ^
src/hashutil.cpp:139:9: error: unknown type name '__m256i'
  const __m256i first = _mm256_set1_epi8('_');
        ^
src/hashutil.cpp:139:25: error: use of undeclared identifier '_mm256_set1_epi8'; did you mean '_mm_set1_epi8'?
  const __m256i first = _mm256_set1_epi8('_');
                        ^~~~~~~~~~~~~~~~
                        _mm_set1_epi8
```

Using a newer compiler than the version of clang included in Xcode may be a viable workaround (open source clang 9.0.1 builds ccache 4.0 just fine on Mac OS X 10.6 and 10.7), and if using a newer compiler is required, that's fine, but my initial assumption was that this was supposed to be compilable by any C++11-compatible compiler, which clang in Xcode 5 and up allegedly is. If a newer compiler is required, it should be documented.

### Expected behavior ###

successful compile

### Environment ###

ccache version 4.0

OS X El Capitan v10.11.6 (15G22010)
Xcode v8.2.1 (8C1002)
Apple LLVM version 8.0.0 (clang-800.0.42.1)

OS X Yosemite v10.10.5 (14F2511)
Xcode v7.2.1 (7C1002)
Apple LLVM version 7.0.2 (clang-700.1.81)

OS X Mavericks v10.9.5 (13F1911)
Xcode v6.2 (6C131e)
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)

OS X Mountain Lion v10.8.5 (12F2560)
Xcode v5.1.1 (5B1008)
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)

**Comment by AlexanderLanin** [comment]
Some problems (probably unrelated to the above) with clang 3.4 / 3.5 will be reproducible by #690.

For older MacOS versions in general we need an alternative to GitHub Actions like Travis 😞

Maybe related to https://bugs.llvm.org/show_bug.cgi?id=25510, but since it did work before it should be fixable.

**Comment by erijo** [comment]
I did an attempt at fixing this on [this branch](https://github.com/erijo/ccache/tree/mac-build). Is it possible for you to test that and see if it works?

**Comment by AlexanderLanin** [comment]
@erijo there is some similarly looking logic in https://github.com/ccache/ccache/blob/master/src/hashutil.cpp#L39
Would it make sense to merge all of that?

It seems detecting avx2 is a well known and complex problem. There is no uniform solution out there as far as I can tell https://github.com/search?q=filename%3Afind_avx.cmake&type=code

**Comment by erijo** [comment]
The logic in hashutil.cpp is a bit different as it deals with working around issues with `__builtin_cpu_support`. What I have been thinking is that it could perhaps be an idea to replace the call to `__builtin_cpu_support` with BLAKE3's run-time detection. But that would require either a ccache local modification to BLAKE3 (making upgrades require slightly more work) or asking BLAKE3 upstream to make the CPU features function public.

**Comment by ryandesign** [comment]
> I did an attempt at fixing this on [this branch](https://github.com/erijo/ccache/tree/mac-build). Is it possible for you to test that and see if it works?

This looks good. I do see another build error after this but it looks unrelated so I'll file a different issue for that.

**Comment by ryandesign** [comment]
With the proposed fix:

* On 10.8 and 10.9 I now see #695.
* On 10.10, I now see these errors that I had seen on 10.8 and 10.9 before:
> ```
> src/hashutil.cpp:128:18: warning: unknown attribute 'target' ignored [-Wattributes]
>   __attribute__((target("avx2")));
>                  ^
> src/hashutil.cpp:139:9: error: unknown type name '__m256i'
>   const __m256i first = _mm256_set1_epi8('_');
>         ^
> src/hashutil.cpp:139:25: error: use of undeclared identifier '_mm256_set1_epi8'; did you mean '_mm_set1_epi8'?
>   const __m256i first = _mm256_set1_epi8('_');
>                         ^~~~~~~~~~~~~~~~
>                         _mm_set1_epi8
> ```
If I change the clang version check from 7.0.0 to 8.0.0 then it builds.
* On 10.11, I now see:
```
Undefined symbols for architecture x86_64:
  "___cpu_model", referenced from:
      check_for_temporal_macros(nonstd::sv_lite::basic_string_view<char, std::__1::char_traits<char> >) in libccache_lib.a(hashutil.cpp.o)
ld: symbol(s) not found for architecture x86_64
```
If I change the clang version check from 7.0.0 to 9.0.0 then it builds.

**Comment by erijo** [comment]
I'm hoping that the fixes in #704 together with what's already merged to master should make ccache build on mac.

**Comment by erijo** [comment]
Is this issue fixed now with the latest master?

**Comment by ryandesign** [comment]
Yes, thank you. ccache 4.1 builds fine with the clang available on OS X 10.10 and later, and on 10.9 and earlier it prints the more helpful message "The compiler you are using is too old, sorry."
