### ISSUE TITLE
building ccache > 4.9.1 on an old Linux without spawn.h fails the build - but is checked in CMake already

### ISSUE THREAD

**Issue by ssproessig-thales** [ccache/ccache#1685]
I'm building ccache on a prehistoric CentOS 6. CMake correctly reports `spawn.h` to not be found

```
[aroadm@arobld-centos6 ccache-4.12.2-build]$ cmake -G Ninja -DHIREDIS_FROM_INTERNET=ON -DZSTD_FROM_INTERNET=ON -DCMAKE_BUILD_TYPE=Release  ../ccache-4.12.2
-- The C compiler identification is GNU 12.5.0
-- The CXX compiler identification is GNU 12.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/aro/bin/gcc-12.5
-- The ASM_MASM compiler identification is unknown
-- Found assembler: ml
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/aro/bin/gcc-12.5 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/aro/bin/g++-12.5 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Ccache version: 4.12.2
-- Ccache dev mode: OFF
-- Performing Test std_atomic_without_libatomic
-- Performing Test std_atomic_without_libatomic - Success
-- Performing Test std_filesystem_without_libfs
-- Performing Test std_filesystem_without_libfs - Success
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for linux/fs.h
-- Looking for linux/fs.h - found
-- Looking for pwd.h
-- Looking for pwd.h - found
-- Looking for spawn.h
-- Looking for spawn.h - not found
....
-- Build files have been written to: /home/aroadm/build-env/ccache-4.12.2-build
```

but finishes configuring with OK. Building then fails in `execute.cpp` where the `#include` is guarded, but not the code using it:

```
/home/aroadm/build-env/ccache-4.12.2/src/ccache/execute.cpp: In function ‘int execute(Context&, const char* const*, util::Fd&&, util::Fd&&)’:
/home/aroadm/build-env/ccache-4.12.2/src/ccache/execute.cpp:293:3: error: ‘posix_spawn_file_actions_t’ was not declared in this scope
```

ccache 4.9.1 is the last version I can build on CentOS 6 where glibc is 2.12.

Suggestion: if `spawn.h` is not found on a Linux (not on _WIN32 would be the #else), fail configuring already in CMake, suggesting to build 4.9.1.

**Comment by jrosdahl** [comment]
Thanks for the suggestion.

I understand where you're coming from, but I don't think it's worth the maintenance cost to keep track of when ccache versions stop working for different OS versions, sorry.

That being said, it doesn't quite make sense to have a CMake check for a header that is actually mandatory. I'll remove it.

**Comment by jrosdahl** [comment]
Removed in 85a885b201d25461d66cfcef98f80698e55dd43b.
