### ISSUE TITLE
MSVC PCH headers with base_dir still not working in Ccache 4.13.2

### ISSUE THREAD

**Issue by notdanhan** [ccache/ccache#1722]
### Problem description

I'm hitting `project\s\libname\CMakeFiles\libname_shared.dir\cmake_pch.cxx(2): error C2857: '#include' statement specified with the /Ycproject\s\libname\CMakeFiles\libname_shared.dir\Release\cmake_pch.hxx command-line option was not found in the source file` when compiling on MSVC using ccache 4.13.2

I'm not sure if I'm using some unanticipated combination of flags or something so I included them below, if there's something I can do to tweak it (by modifying ccache itself or by changing something in teh cmake or whatever), lemme know!

### How to reproduce the problem

msvc version 14.44
ccache is set as follows in cmake
```
cmake_path(SET CCACHE_BUILDS_DIR NORMALIZE "${CMAKE_SOURCE_DIR}/../")
        cmake_path(SET CCACHE_CACHE_DIR NORMALIZE "${CMAKE_SOURCE_DIR}/../ccache")
        message(NOTICE "-- CCache Cache Directory: ${CCACHE_CACHE_DIR}")
        set(ccacheOpts "${CCACHE_EXE};base_dir=${CCACHE_BUILDS_DIR};cache_dir=${CCACHE_CACHE_DIR};hash_dir=false;sloppiness=pch_defines,time_macros,include_file_mtime,include_file_ctime")
        message(NOTICE "-- Enabling CCache with the following options ${ccacheOpts}")
        set(CMAKE_C_COMPILER_LAUNCHER ${ccacheOpts})
        set(CMAKE_CXX_COMPILER_LAUNCHER ${ccacheOpts})
```

```
path\to\ccache.exe base_dir=D:/builds/ cache_dir=D:/builds/ccache hash_dir=false sloppiness=pch_defines,time_macros,include_file_mtime,include_file_ctime path\to\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe  /nologo /TP -DNOMINMAX -DNTDDI_VERSION=0x06020000 -DUNICODE -DWIN32 -DWIN64 -DWINVER=0x0602 -D_DISABLE_STRING_ANNOTATION -D_UNICODE -D_WIN32_WINNT=0x0602 -D_WINDOWS -DCMAKE_INTDIR=\"Release\" -Ipath\to\includes -external:ID:\some\external\library -external:W0 /DWIN32 /D_WINDOWS  /O2 /Ob2 /DNDEBUG -std:c++latest -MD -Z7 /GL /X /bigobj /EHac /Oy- /Zo /Zc:preprocessor /GR /GF /Gw /Gy /Zc:__cplusplus /permissive- /Zc:char8_t- /utf-8 /Zc:enumTypes /Zc:externConstexpr /Zc:inline /Zc:throwingNew /Zc:templateScope /volatile:iso /W4 /we4033 /we4172 /we4715 /we4716 /we4717 /wd4373 /WX /wd4702 /we6244 /YcD:/builds/build-w64/project/s/libname/CMakeFiles/libname_shared.dir/Release/cmake_pch.hxx /FpD:/builds/build-w64/project/s/libname/CMakeFiles/libname_shared.dir/Release//cmake_pch.cxx.pch /FID:/builds/build-w64/project/s/libname/CMakeFiles/libname_shared.dir/Release/cmake_pch.hxx /showIncludes /Foproject\s\libname\CMakeFiles\libname_shared.dir\Release\cmake_pch.cxx.obj /Fdproject\s\libname\CMakeFiles\libname_shared.dir\Release\ /FS -c D:\builds\build-w64\project\s\libname\CMakeFiles\libname_shared.dir\cmake_pch.cxx
```

### Actual behavior

error C2857: '#include' statement specified with the /Ycproject\s\libname\CMakeFiles\libname_shared.dir\Release\cmake_pch.hxx command-line option was not found in the source file

### Expected behavior

it to work

### Ccache version

4.13.2

### Ccache configuration

hash_dir=false;sloppiness=pch_defines,time_macros,include_file_mtime,include_file_ctime

### Operating system

Windows

### Logs

```shell

```
