### ISSUE TITLE
MSVC crash with ccache 4.9 when using /Zi /Fddebug.pdb

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#1386]
### How to reproduce ###

Run many parallel invocations of ccache wrapping MSVC with options `/Zi /Fddebug.pdb`, i.e. writing to the same PDB file. High I/O load on the machine might help to trigger the problem.

### Actual behavior ###

`cl.exe` crashes with this error message:

```
fatal error C1090: PDB API call failed, error code '23': (0x000006BA)
```

### Expected behavior ###

The compilation does not crash.

### Environment ###

ccache version 4.9.

The problem was introduced in 8e3ada3f830ad0e7d3ddf4eaf2b16e695bd084e4 (#1274).
